---
deployment:
  tasks:
    - /bin/cp -R public/* /home/qbocorredoresdes/public_html/
    - /bin/cp public/.htaccess /home/qbocorredoresdes/public_html/.htaccess
    - /bin/chmod -R 775 /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage
    - /bin/chmod -R 775 /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/bootstrap/cache
    - /bin/mkdir -p /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage/framework/sessions
    - /bin/mkdir -p /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage/framework/views
    - /bin/mkdir -p /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage/framework/cache/data
    - /bin/mkdir -p /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage/logs
    - /bin/rm -rf /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/storage/framework/views/*.php
    - /bin/rm -rf /home/qbocorredoresdes/repositories/bqcorredoresdeseguros2/bootstrap/cache/*.php
